### ISSUE TITLE
list of art alternatives

### ISSUE THREAD

**Issue by vroland** [vroland/epdiy-hardware#3]
As requested in https://github.com/vroland/epdiy/issues/260, it would be useful to have a comprehensive list of part alternatives that are cheaper / more available, like TPS651851/TPS65185, schottky diodes, FPC connectors, etc.

**Comment by martinberlin** [comment]
I can contribute with one:

XF2M-3315-1A | Omron 9.7" 33 pin connector | C231420  is currently 3.2 $ (Last time wanted to pre-order 20)
This could be replaced for cheaper C597986, Hirose connector which is 0.50 usd when buying 30 and up to 70 cents when buying less quantity.

For me the only important point of FPC connectors apart that they must have the same 0.5 mm pitch is that they have only bottom connection. Double-sided are dangerous since connecting displays in the opposite way you can send voltages to pins that only are supposed to get 3.3V and damage your PCB (Or the display)

**Comment by martinberlin** [comment]
Proposed format:
https://github.com/vroland/epdiy-hardware/wiki/Alternative-components
Feel free to expand and add a new column to the table if needed.

**Comment by vroland** [comment]
Thanks!
I moved this to a markdown file to make contributing easier, and it's now also built into the presentation page :)
