### ISSUE TITLE
v7 board does not specify display type on the silkscreen

### ISSUE THREAD

**Issue by hramrach** [vroland/epdiy-hardware#7]
Up to v6 board the silksceen would have exact display type, while v7 only has the pin count. As the ED133UT2 adapter attests pin count is not sufficient to determine the screen type.

As such going from screen type to pin count looks like a regression to me.

**Comment by martinberlin** [comment]
Just my opinion: I disagree.
Epdiy really drives many different Eink displays that are specified in the table on the repository index. Having the pin count is the right thing to do since you cannot just list all the different models in the silkscreen.
All have the same driving principle so all that matters is the pin count and that connector matches, all the rest should be solved in the firmware

**Comment by hramrach** [comment]
> Epdiy really drives many different Eink displays that are specified in the table on the repository index. Having the pin count is the right thing to do since you cannot just list all the different models in the silkscreen. All have the same driving principle so all that matters is the pin count and that connector matches, all the rest should be solved in the firmware

And that's exactly the problem, this is not true. ED060SC4 and ED133UT2 use exactly the same connector, and same driving principle but completely different pinout. The pinout of the 33pin connector is compatible with ED060SC4 but if you connect ED133UT2 to it without the correct adapter it will not work and likely burn down. The pinout of the 33pin connector is for ED060SC4 and isplays with compatible pinout, and not for ED133UT2. This was clear with the previous revision looking at the silkscreen, with the latest revision this information is lost.

**Comment by martinberlin** [comment]
> ED060SC4 and ED133UT2 use exactly the same connector 

sure in this I agree. But first things first: [Official v7 PCB](https://github.com/vroland/epdiy/blob/main/doc/source/img/hardware_page.png) does NOT have a 39 pin connector so I don’t really see why it should mention either of those models

![5ED17F02-EB60-44DA-B024-4BC926DECDAC](https://github.com/vroland/epdiy-hardware/assets/2692928/8b2566f7-a7a0-472e-b2e0-fd052a23b8c6)

I did make my own v7 for and added a 13.3” connector but signaled what display its for in the Silkscreen 
![056C4CE3-5B65-41CB-9569-13B2CB6A0FDE](https://github.com/vroland/epdiy-hardware/assets/2692928/336de3e0-caef-4974-a634-5eb6b0662523)

**Comment by martinberlin** [comment]
I would simply add the size like:
33 pins 9.7”
34 pins 6” and if someone needs to adapt it just add the particular display name
40 is 16 bits and there are many different models that use it from Eink to Wuxi Weifeng DES and maybe more

Ideally the concept of adding 3 different FPC connectors is that mostly you leave just the one that you will use for your project. Having 3 is to facilitate the first time testers to get on board without complications.
I would personally avoid as much as possible to use adapters.

**Comment by hramrach** [comment]
> 33 pins 9.7” 
At which point you are back to the specific display model, except in a vague, roundabout way.

**Comment by martinberlin** [comment]
This board is open source and actually everyone can edit it before sending it to fabrication and personalize it to their needs. I do not see any functional issue and for me the v7 has the right silkscreen.
I do not see any point to name it differently since 9.7 could be ED097TC2 for some users, or ED097OC1 for others, or any other 33 pin displays with same pin-out.
